---
add_packages:
  - libgtk2.0-0
  - libxrandr2
  - libxdamage1
  - libxcursor1
  - libxcomposite1 
  - libxext6
  - libxfixes3
  - libxrender1
  - libx11-6
  - libxtst6
  - libxss1
  - libgconf2-4
  - libnss3
  - libnspr4
  - libasound2
  - libcups2
  - libdbus-1-3
  - libxkbfile1
  - libx11-xcb1
  - libsecret-1-0
  - git
  - curl
  - python
  - xz-utils

platform:
  null: null

sdk:
  add_packages:
    - fakeroot
    - dpkg-dev
...
